sonar.projectKey=ag-kidsapp
sonar.projectName=ag-kidsapp
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.js,**/*.test.ts,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
