sonar.organization=prithvisuri
sonar.projectKey=prithvisuri_ag-kidsapp-1
sonar.projectName=ag-kidsapp
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts
sonar.exclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,src/styles/**
sonar.coverage.exclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,src/styles/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
