name: ag-kidsapp
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v7
      - name: install nodejs
        uses: actions/setup-node@v7
        with:
          node-version: '22'
      - name: install dependencies
        run: npm install 
      - name: run build
        run: npm run build
      - name: mpm tests
        run: npm test

      # New step to create and upload the artifact
      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ag-kids-production-files # The name of your downloadable zip file
          path: dist/ # The folder or file you want to save (e.g., dist, build, or out)
